
version: '3'
services:
  reminderbot:
    image: playball/reminderbot:latest
    restart: always
    container_name: reminderbot
    env_file:
      - '.env.prod'
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600 reminderbot